/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Compilador.Compilador;
import java.util.ArrayList;

/**
 *
 * @author astridmc
 */
public class ListarLenguajes extends javax.swing.JDialog {

    /**
     * Creates new form ListarLenguajes
     */
    public ListarLenguajes(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        LlenarCOmbo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLenguaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLenguaje1 = new javax.swing.JLabel();
        lblLenguaje2 = new javax.swing.JLabel();
        box = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();

        lblLenguaje.setBackground(new java.awt.Color(4, 75, 107));
        lblLenguaje.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblLenguaje.setForeground(new java.awt.Color(254, 254, 254));
        lblLenguaje.setText("Aun No ha Seleccionado un Lenguaje");
        lblLenguaje.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 213, 183));
        jPanel1.setForeground(new java.awt.Color(101, 213, 183));

        lblLenguaje1.setBackground(new java.awt.Color(4, 75, 107));
        lblLenguaje1.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblLenguaje1.setForeground(new java.awt.Color(254, 254, 254));
        lblLenguaje1.setText("ESCOJA EL O LOS LENGUAJES ");
        lblLenguaje1.setOpaque(true);

        lblLenguaje2.setBackground(new java.awt.Color(4, 75, 107));
        lblLenguaje2.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblLenguaje2.setForeground(new java.awt.Color(254, 254, 254));
        lblLenguaje2.setText("A ELIMINAR");
        lblLenguaje2.setOpaque(true);

        box.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        btnAceptar.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(lblLenguaje1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblLenguaje2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLenguaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLenguaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int seleccionado = box.getSelectedIndex();
        Principal.compiladores.remove(seleccionado);
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    public void LlenarCOmbo(){
        ArrayList<Compilador> comp = Principal.compiladores;
        for (int i = 0; i < comp.size(); i++) {
             box.addItem(comp.get(i).getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLenguaje;
    private javax.swing.JLabel lblLenguaje1;
    private javax.swing.JLabel lblLenguaje2;
    // End of variables declaration//GEN-END:variables
}
