/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Compilador.Compilador;
import Backend.Compilador.ManejadorArchivo;
import Backend.CupYFlex.AnalizadorLexico;
import Backend.CupYFlex.parser;
import Backend.LectorArchivo;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author astridmc
 */
public class Principal extends javax.swing.JFrame {

    boolean editor = false;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        panelEditor.setVisible(false);
        diseño();
    }

    int compiladorUso;
    public static ArrayList<Compilador> compiladores = new ArrayList();
    ArrayList<String> formatos = new ArrayList();
    ArrayList<Editor> documentos = new ArrayList();
    ArrayList<File> files = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        imagenPanel = new javax.swing.JPanel();
        panelEditor = new javax.swing.JPanel();
        lblLenguaje = new javax.swing.JLabel();
        panelArchivos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNuevo = new javax.swing.JMenuItem();
        btnAbrir = new javax.swing.JMenuItem();
        btnGuardar = new javax.swing.JMenuItem();
        btnGuardarComo = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnLenguajes = new javax.swing.JMenu();
        btnEjecutar = new javax.swing.JMenu();
        btnCompilar = new javax.swing.JMenuItem();
        btnCargarL = new javax.swing.JMenuItem();
        btnBorrarL = new javax.swing.JMenuItem();
        btnLALR = new javax.swing.JMenu();
        btnTabla = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 46, 93));

        imagenPanel.setBackground(new java.awt.Color(83, 8, 78));
        imagenPanel.setForeground(new java.awt.Color(83, 8, 78));
        imagenPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPanelComponentResized(evt);
            }
        });

        panelEditor.setBackground(new java.awt.Color(173, 238, 254));

        lblLenguaje.setBackground(new java.awt.Color(4, 75, 107));
        lblLenguaje.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblLenguaje.setForeground(new java.awt.Color(254, 254, 254));
        lblLenguaje.setText("Aun No ha Seleccionado un Lenguaje");
        lblLenguaje.setOpaque(true);

        panelArchivos.setBackground(new java.awt.Color(173, 238, 254));
        panelArchivos.setFont(new java.awt.Font("Waree", 0, 20)); // NOI18N
        panelArchivos.setOpaque(true);
        panelArchivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelArchivosKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelArchivosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelEditorLayout = new javax.swing.GroupLayout(panelEditor);
        panelEditor.setLayout(panelEditorLayout);
        panelEditorLayout.setHorizontalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addComponent(lblLenguaje)
                .addGap(0, 285, Short.MAX_VALUE))
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelArchivos)
                .addContainerGap())
        );
        panelEditorLayout.setVerticalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addComponent(lblLenguaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(4, 35, 74));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(120, 217, 221));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 51));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 40));

        jMenu1.setBackground(new java.awt.Color(77, 183, 175));
        jMenu1.setForeground(new java.awt.Color(1, 1, 1));
        jMenu1.setText(" ARCHIVO ");
        jMenu1.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        jMenu1.setOpaque(true);

        btnNuevo.setBackground(new java.awt.Color(185, 240, 234));
        btnNuevo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(btnNuevo);

        btnAbrir.setBackground(new java.awt.Color(143, 235, 220));
        btnAbrir.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(btnAbrir);

        btnGuardar.setBackground(new java.awt.Color(185, 240, 234));
        btnGuardar.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(btnGuardar);

        btnGuardarComo.setBackground(new java.awt.Color(143, 235, 220));
        btnGuardarComo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnGuardarComo.setText("Guardar Como");
        btnGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(btnGuardarComo);

        btnSalir.setBackground(new java.awt.Color(185, 240, 234));
        btnSalir.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        btnLenguajes.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 2, 0));
        btnLenguajes.setForeground(new java.awt.Color(1, 1, 1));
        btnLenguajes.setText(" LENGUAJES ");
        btnLenguajes.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        jMenuBar1.add(btnLenguajes);

        btnEjecutar.setBackground(new java.awt.Color(77, 183, 175));
        btnEjecutar.setForeground(new java.awt.Color(1, 1, 1));
        btnEjecutar.setText(" EJECUTAR ");
        btnEjecutar.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        btnEjecutar.setOpaque(true);

        btnCompilar.setBackground(new java.awt.Color(185, 240, 234));
        btnCompilar.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnCompilar.setText("Compilar");
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });
        btnEjecutar.add(btnCompilar);

        btnCargarL.setBackground(new java.awt.Color(143, 235, 220));
        btnCargarL.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnCargarL.setText("Cargar Lenguaje");
        btnCargarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarLActionPerformed(evt);
            }
        });
        btnEjecutar.add(btnCargarL);

        btnBorrarL.setBackground(new java.awt.Color(185, 240, 234));
        btnBorrarL.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnBorrarL.setText("Borrar Lenguaje");
        btnBorrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarLActionPerformed(evt);
            }
        });
        btnEjecutar.add(btnBorrarL);

        jMenuBar1.add(btnEjecutar);

        btnLALR.setForeground(new java.awt.Color(1, 1, 1));
        btnLALR.setText(" VER ");
        btnLALR.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N

        btnTabla.setBackground(new java.awt.Color(143, 235, 220));
        btnTabla.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnTabla.setText("Tabla LALR");
        btnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaActionPerformed(evt);
            }
        });
        btnLALR.add(btnTabla);

        jMenuBar1.add(btnLALR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JLabel imagen = new JLabel();
    String fondo = "src/Frontend/Imagenes/fondo2.jpg";
    ImageIcon portada = new ImageIcon(fondo);
    private void imagenPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPanelComponentResized
        if (imagenPanel.getComponents().length > 0) {
            imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
            imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
            imagenPanel.remove(imagen);
            imagenPanel.add(imagen);

        }
    }//GEN-LAST:event_imagenPanelComponentResized

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NombrarDialog nombrar = new NombrarDialog(this);
        nombrar.setVisible(true);

        String nombre = nombrar.getNombre();
        if (editor == false) {
            if (nombrar.getNombre() == null) {
                nombrar.setVisible(false);
            } else {
                editor = true;
                panelEditor.setVisible(true);
            }

        }

        verificarExistenciaTab(nombre, null);
        formatos.add(nombre);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("TEXT FILES", "len");
        //fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            File fileName = fileChooser.getSelectedFile();
            if ((fileName == null) || (fileName.getName().equals(""))) {
            } else {

                try {
                    verificarExistenciaTab(fileName.getName(), fileName);
                    formatos.add(fileName.getName());
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "Error cargando Archivo");
                }
                // txt.setText(fileName.getAbsolutePath());
            }
        }

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Compilador comp = compiladores.get(compiladorUso);
        if (comp != null) {
            int indice = panelArchivos.getSelectedIndex();
            if (comp.getExtension() != null && comp.getNombre() != null) {
                if (documentos.get(indice).getDocumento() == null) {
                    NombrarDialog nombrar = new NombrarDialog(this);
                    nombrar.setVisible(true);
                    String nombre = nombrar.getNombre();
                    JFileChooser chooser = new JFileChooser();
                    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                    int result = chooser.showOpenDialog(this);
                    if (result == JFileChooser.APPROVE_OPTION) {
                        ManejadorArchivo.GuardarArchivo(chooser.getSelectedFile().getAbsolutePath() + "." + comp.getExtension(), documentos.get(indice).ObtenerTexto());
                    }
                } else {
                    String texto = documentos.get(indice).ObtenerTexto();
                    File archivo = documentos.get(indice
                    ).getDocumento();
                    LectorArchivo lector = new LectorArchivo();
                    lector.GuardarTexto(archivo, texto);
                }

            } else if (comp.getNombre() != null) {

            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComoActionPerformed
        NombrarDialog nombrar = new NombrarDialog(this);
        nombrar.setVisible(true);
        Compilador comp = compiladores.get(compiladorUso);
        int indice = panelArchivos.getSelectedIndex();
        String nombre = nombrar.getNombre();
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            ManejadorArchivo.GuardarArchivo(chooser.getSelectedFile().getAbsolutePath() + "." + comp.getExtension(), documentos.get(indice).ObtenerTexto());
        }
    }//GEN-LAST:event_btnGuardarComoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void btnCargarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarLActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("TEXT FILES", "len");
        fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            File fileName = fileChooser.getSelectedFile();
            if ((fileName == null) || (fileName.getName().equals(""))) {
            } else {
                try {
                    AnalizadorLexico lexico = new AnalizadorLexico(new BufferedReader(new StringReader(ManejadorArchivo.leerArchivo(fondo))));
                    parser parser1 = new parser(lexico);
                    parser1.parse();
                } catch (Exception ex) {
                    System.out.println("error ..." + ex);
                }
            }
        }
        CargarNuevoLenguaje();
    }//GEN-LAST:event_btnCargarLActionPerformed

    private void btnBorrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLActionPerformed
        ListarLenguajes listar = new ListarLenguajes(this);
        listar.setVisible(true);
        CargarNuevoLenguaje();
    }//GEN-LAST:event_btnBorrarLActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTablaActionPerformed

    private void panelArchivosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelArchivosKeyTyped

    }//GEN-LAST:event_panelArchivosKeyTyped

    private void panelArchivosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelArchivosKeyPressed

    }//GEN-LAST:event_panelArchivosKeyPressed

    void diseño() {
        setTitle("COMPILADOR");
        setLocation(200, 100);
        setIconImage(new ImageIcon("src/Frontend/Imagenes/icono.png").getImage());
        imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
        imagenPanel.add(imagen);
    }

    void CargarNuevoLenguaje() {
        btnLenguajes.removeAll();

        for (int i = 0; i < compiladores.size(); i++) {
            JMenuItem boton = new JMenuItem();
            boton.setText(compiladores.get(i).getNombre());
            boton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    compiladorUso = buscarCompilador(boton.getText());
                    if (compiladorUso >= 0 && compiladores.size() > 0) {
                        lblLenguaje.setText("El lenguaje Seleccionado es " + boton.getText());
                    } else {
                        lblLenguaje.setText("Aun No ha Seleccionado un Lenguaje");
                    }
                }
            });
            btnLenguajes.add(boton);
        }
    }

    /**
     * @param args the command line arguments
     */
    public JPanel createTabHead(String title) {
        JPanel pnlTab = new JPanel();
        pnlTab.setLayout(new BoxLayout(pnlTab, BoxLayout.LINE_AXIS));
        pnlTab.setOpaque(false);
        JButton btnClose = new JButton("x");
        JLabel lblTitle = new JLabel(title + "    ");
        btnClose.setBorderPainted(false);
        btnClose.setOpaque(false);

        btnClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int i;
                for (i = 0; i <= panelArchivos.getTabCount() - 1; i++) {
                    if (title.equals(panelArchivos.getTitleAt(i))) {
                        break;
                    }
                }
                if (JOptionPane.showConfirmDialog(panelArchivos, "DESEA CERRAR EL GUARDAR EL ARCHIVO?") == 0) {
                    panelArchivos.removeTabAt(i);
                    String texto = documentos.get(i).ObtenerTexto();
                    File archivo = documentos.get(i).getDocumento();
                    LectorArchivo lector = new LectorArchivo();
                    lector.GuardarTexto(archivo, texto);
                    formatos.remove(i);
                    documentos.remove(i);
                } else {
                    panelArchivos.removeTabAt(i);
                    formatos.remove(i);
                    documentos.remove(i);
                }

            }
        });

        pnlTab.add(lblTitle);
        pnlTab.add(btnClose);
        return pnlTab;
    }

    public void verificarExistenciaTab(String nombre, File doc) {
        boolean aux = false;
        int i = 0;
        for (i = 0; i < formatos.size(); i++) {
            if (nombre.equals(formatos.get(i))) {
                aux = true;
                break;
            } else {
                aux = false;
            }
        }
        if (aux) {
            JOptionPane.showMessageDialog(rootPane, "ya tiene un documento con ese mismo nombre");
        } else if (!aux) {
            Editor editor = new Editor("");
            editor.setDocumento(doc);
            documentos.add(editor);
            panelArchivos.addTab(nombre, editor);
            int index = panelArchivos.indexOfTab(nombre);
            panelArchivos.setTabComponentAt(index, createTabHead(nombre));
        }
    }

    public int buscarCompilador(String comp) {
        for (int i = 0; i < compiladores.size(); i++) {
            if (comp.equals(compiladores.get(i).getNombre())) {
                return i;
            } else {
                return -1;
            }
        }
        return -1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbrir;
    private javax.swing.JMenuItem btnBorrarL;
    private javax.swing.JMenuItem btnCargarL;
    private javax.swing.JMenuItem btnCompilar;
    private javax.swing.JMenu btnEjecutar;
    private javax.swing.JMenuItem btnGuardar;
    private javax.swing.JMenuItem btnGuardarComo;
    private javax.swing.JMenu btnLALR;
    private javax.swing.JMenu btnLenguajes;
    private javax.swing.JMenuItem btnNuevo;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnTabla;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLenguaje;
    private javax.swing.JTabbedPane panelArchivos;
    private javax.swing.JPanel panelEditor;
    // End of variables declaration//GEN-END:variables
}
