
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 02 23:10:06 CST 2020
//----------------------------------------------------

package Backend.CupYFlex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GUION = 26;
  public static final int PUNTO = 3;
  public static final int TERMINALID = 9;
  public static final int PUNTOYCOMA = 23;
  public static final int DOSPUNTOS = 22;
  public static final int JAVACODE = 11;
  public static final int IGUAL = 14;
  public static final int CODIGOJ = 32;
  public static final int TABULADOR = 28;
  public static final int EXTENSIONID = 8;
  public static final int ID = 12;
  public static final int COMA = 33;
  public static final int SIMMAS = 30;
  public static final int LLAVECIERRA = 16;
  public static final int NOTERMINALID = 10;
  public static final int BARRAO = 25;
  public static final int PORCIENTO = 13;
  public static final int ASTERISCO = 21;
  public static final int EOF = 0;
  public static final int DIGITO = 2;
  public static final int ESPACIOBLANCO = 29;
  public static final int NOMBREID = 4;
  public static final int COMILLA = 31;
  public static final int error = 1;
  public static final int INTERROGACIONC = 24;
  public static final int CORCHETEABRE = 18;
  public static final int SALTOLINEA = 27;
  public static final int PARCIERRA = 20;
  public static final int PARABRE = 19;
  public static final int CORCHETECIERRA = 17;
  public static final int AUTORID = 6;
  public static final int VERSIONID = 5;
  public static final int LANZAMIENTOID = 7;
  public static final int LLAVEABRE = 15;
}

